[theme]
base = "light"
primaryColor = "#087f72"
backgroundColor = "#f4f7f5"
secondaryBackgroundColor = "#f0f4f0"
textColor = "#182d36"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
fileWatcherType = "auto"
runOnSave = true
